00-einführung:
  source: 00-einführung.rst
  css:
    - css/campus02.css
  template: default
  auto-console: false
  skip-help: true
  skip-notes: true
01-fileio:
  source: 01-fileio.rst
  css:
    - css/campus02.css
  template: default
  auto-console: false
  skip-help: true
  skip-notes: true
  assets:
    - figures
    - images
02-networkio:
  source: 02-networkio.rst
  css:
    - css/campus02.css
  template: default
  auto-console: false
  skip-help: true
  skip-notes: true
  assets:
    - figures
    - images
